// East Slovak ("vychodňarsky") trash talk, callouts and announcer lines.
// {v} = victim, {k} = killer, {z} = zone, {s} = site, {a} = attacker, {h} = human who wrote in chat.
import { TEAM_NAME } from './config.js';

const L = {
  kill: [
    'Mam ce, {v}, ty debiľe!',
    'Ta co, {v}, zaspal ši? Kurva drat!',
    'Idz do rici, {v}!',
    'Tak ci treba, hovado jedno!',
    'Ši slabi jak čaj z bufetu, {v}!',
    'Ľem jeden strel a ľežiš, ty mamľas!',
    'Chodz še učic strilac, ty ľemro!',
    'Jebem ci na tvoj aim, {v}!',
    'Ta ši ňebul pripraveni, co? Hehe.',
    'Zbohom, {v}, pozdravuj mamku!',
    'Aňi ši ňezbačil, dze ce trafilo, kokocin!',
    'Dalši do vreca, kurva!',
    'Ta co, {v}, ľubiš zem? Ta ju bozkaj!',
    'Jebnuty jak lopata, {v}!',
    'Mamka ci ňepovedala, že ši ľemra?',
    'Na, maš, kokocino jedno!',
    'Ľežiš tam jak vrece zemakov, hehe!',
    'Idz še radšej hrac s babkami, {v}!',
    'Dzeci v škole strilaju lepši jak ty, {v}!',
    'Ščesľivu cestu, ty hovado!',
    'Do rici s tebu, {v}, šak ši ňic ňevedzel!',
    'Kurva drat, jake to bulo ľahke!',
    'Pozdravuj Pana Boha, {v}!',
    '{v}, ši slabši jak kofola bez bubliňek!',
    'Chceš ešči? Mam dosc naboji, ty cicak!',
    'Zdochňi, {v}, a ňekempuj mi tu!',
  ],
  headshot: [
    'Rovno do kotrby, kurva drat!',
    'Do hlavy, {v}! Taki som ja!',
    'Hlavička, ta co ši čekal, debiľe?',
    'Prazdna hlava, aľe trafil som ju, hehe!',
    'Bum do čela, jak na jarmaku!',
    'Z hlavy ci zrobil cedzak, {v}!',
    'Trefil som ci rovno do tej tvojej dutej tekvice!',
    'Pif paf do čela, a ty už ňič ňevidziš!',
    'Taki headshot ci ňezrobi aňi tvoj fotr!',
    'Kotrba preč, kurva drat!',
    'Do hlavy, jak keby som ľem pľuvnul!',
  ],
  death: [
    'Kurva, dze to strilal?!',
    'Ta to ňemožne, ja som ho mal!',
    'Lag, kurva, lag!',
    'Do rici, {k}, ešči ce najdzem!',
    'Ňevidzel som ho, na moju dušu!',
    'Ruka še mi posmykla, ňič vecej.',
    'Jebem to, idzem na pivo.',
    '{k}, ty kurvin synu!',
    'Ta co to bulo za chujovinu?!',
    'Hekuje, kurva, určite hekuje!',
    'Kurva, kurva, kurva!',
    'Kto to bul, ten skurvysyn?!',
    'Zabil me, ta bars ďakujem, ty hovado!',
    'Myš mi zdochla, prisaham!',
    'Ta co to za kokotinu tu mace?!',
    '{k}, ešči raz a ce najdzem aj doma!',
    'Ja ňevidzel ňič, šak to kempuje ten ľemra!',
    'Kurva, zas ja, zas ja!',
    'Ta ja už ňehram, do rici!',
  ],
  hurt: [
    'Au, kurva, to bolelo!',
    'Trafil me, ten debil!',
    'Kurva, krvacim jak prasa!',
    'Au, moja riť!',
    'Kto to strilal? Pomoc, kurva!',
    '{a}, ty skurvysyn, aňi trafic ňevieš poriadne!',
    'Ešči žijem, ty ľemro, mier lepši!',
    'Au au au, jebem ci mater!',
  ],
  taunt: [
    'Dze ste, kurvy? Ja vas najdzem!',
    'Hrame dneska, abo ľem chodzime?',
    'Chlapci, šak dneska ich rozjebeme!',
    'Ked ich stretnem, ta jim dam, že budu plakac!',
    'Ta co, kempujece jak babky na lavičke?',
    'Dajce mi daco zabic, lebo še ňudzim!',
    'Kto ma borovičku? Po kole pijeme!',
    'Ta bežme, lemre, šak ňe je ňedzeľa!',
    'Jebem to, idzem sam!',
    'Ta šak ste pomalši jak moja babka s palicu!',
    'Kto bul včera na zabave? Kurva, še mi hlava rozpada!',
    'Ta dajce še, kokoci, šak vas počujem!',
    'Buďce ticho, lemre, počuvam kroky!',
    'Po zapase idzeme na kebab, ja platim!',
    'Ta ja bym zjedol vyprážaný syr, kurva, hlad jak vlk!',
  ],
  reload: ['Nabijam, kryjce me, do rici!', 'Mam prazdne, kurva, chvilku!', 'Ňemam naboje, jebem to!'],
  buy: [
    'Kupce si daco poriadne, ňe ľem nožik, lemre!',
    'Kupujce zbrane, ňe cukriky!',
    'Ta ja ňemam aňi na vestu, kurva!',
    'Kto mi požiča peňeži? Vracim v piatek!',
    'Šicki ku mňe, mam plan!',
    'Dneska bez kempovania, lemre, idzeme napredok!',
  ],
  multi: ['Trojička, kurva drat!', 'Ta ja som dneska jak Rambo!', 'Šickich pozabijam, šickich!', 'Kurva, ja som dneska bomba!'],
  lastAlive: [
    'Ta ja som ostal sam? Jebem vas šickych!',
    'Ostal som ľem ja, ta modlce še!',
    'Sam proci šickym, jak Jánošík!',
    'Kurva, ta dze ste šicki?',
  ],
  bombCT: ['Bomba tika, bežme, kurva!', 'Kto ma kit? Rychlo na bombu!', 'Ta ňestujce, bomba!'],
  reply: [
    'Ta čuš, {h}, ty mamľas!',
    'Piš menej a strilaj vecej, {h}!',
    '{h}, ta ci ňerozumim, hovoriš jak koza!',
    'Ta jasne, {h}, ľem kec!',
    'Aňi ňepiš, {h}, radšej trenuj!',
    'Ta ňekecaj, {h}, aľe hraj!',
  ],
  eat: [
    'Mňam, vyprážaný syr, to je život!',
    'Syr s hranolkami, kurva, jak u mamky!',
    'Tatarka mohla byc hustejša, aľe dobre!',
    'Ešči jeden syr a som jak novy!',
  ],
  plant: [
    'Bomba je pod, chlapci, držce to do rici!',
    'Podložene! Teraz ľem čekac a kryc!',
    'Tik tak, kurva, tik tak!',
    'Bomba tika, a vy ste v riti, policajti!',
  ],
  defuseStart: [
    'Kryjce me, idzem na bombu!',
    'Zneškodňujem, ňech mi ňichto ňeskače do toho!',
    'Drotiky režem, ňerušce me, kurva!',
  ],
  defused: [
    'Hotovo, ta ňebulo to take ťažke, lemry.',
    'Zneškodnene! Pivo na mňe.',
    'Červeny drot, jasne, že červeny, kurva!',
  ],
  bombDropped: [
    'Kurva, bomba je na zemi, dachto ju zobrac!',
    'Kto spuscil bombu, ty debiľe?!',
    'Bomba ľeži jak ľemra, zoberce ju!',
  ],
  flashed: [
    'Ňevidzim ňič, kurva! Kto to hodzil?!',
    'Oči mi vypaľilo, do rici!',
    'Bila tma, jebem to!',
    'Ta som sľepy jak krt, kurva!',
  ],
  he: ['Granat leci, chovajce rici!', 'Bum idze, chlapci!', 'Na, maš darček, kurva!'],
  flash: ['Flešak, zatvarajce oči!', 'Švetlo idze, lemre!', 'Oči zatvarac, ľemre!'],
  smoke: ['Dym, ňič ňevidzice, hehe!', 'Dimovnica leci!', 'Dym jak v krčme, hehe!'],
  spot: [
    'Ňepriateľ na {z}!',
    'Dajaki chujik na {z}!',
    'Pozor, su na {z}!',
    'Vidzim ich na {z}, kurva!',
    'Kurva, idu na {z}!',
    'Jeden kokot na {z}!',
  ],
  win: [
    'Šumne, chlapci, dneska pijeme borovičku!',
    'Ta vidzice, jak še to robi, lemry?',
    'Iďce še vyplakac k mamke!',
    'Ľahko jak z kopca, kurva!',
    'Idzeme na kebab, vyhrali sme, kurva!',
    'Taki paradny kolo, aš mi slzy idu!',
  ],
  lose: [
    'Kurva, ta co robice, ľudze?!',
    'S takima debilami ja ňebudzem hrac!',
    'Ešči raz a idzem domu, do rici!',
    'Ta to je hamba jak pes.',
    'Jebem to, ta aňi babka by tak ňeprehrala!',
    'Kurva, ta dze ste buľi, keď som vas treboval?',
  ],
  lowTime: ['Ta pohňice še, lemry, čas idze!', 'Kurva, šak ňemame čas, bežce!'],
  planT: ['Idzeme na {s}, šicki za mnu!', 'Dneska {s}, ta ňezaspice mi tam!', 'Rush {s}, kurva, bez zastavovania!'],
  planCT: ['Ja držim {s}, ňech mi ňichto ňebere mesto.', 'Idzem na {s}, kryjce mi chrbet.', 'Na {s} ja, ta ňech pridu, kurvy!'],
};

const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];

export function line(kind, vars = {}) {
  const list = L[kind];
  if (!list) return '';
  return pick(list).replace(/\{(\w)\}/g, (_, k) => vars[k] ?? '');
}

const ANN_EN = {
  matchStart: () => 'Match start',
  round: (n) => `Round ${n}`,
  buyPhase: 'Buy phase — press <b>B</b> to buy',
  go: () => 'GO GO GO!',
  planted: 'The bomb has been planted',
  plantedSub: (s) => `Bombsite ${s} · 40 seconds`,
  win: (team) => `${TEAM_NAME[team]} Win`,
  reasons: { elim: 'All enemies eliminated', bomb: 'Target successfully bombed', defuse: 'The bomb has been defused', time: 'Time ran out' },
  mvp: 'MVP',
  killedBy: (k, w, hs) => `Killed by ${k} · ${w}${hs ? ' · headshot' : ''}`,
  died: 'You died',
  sayPlanted: () => 'The bomb has been planted.',
  sayDefused: () => 'The bomb has been defused.',
  sayWin: (team) => `${TEAM_NAME[team]} win.`,
  sayNade: { he: 'Fire in the hole!', flash: 'Flashbang out!', smoke: 'Smoke out!' },
  ate: (hp) => `Fried cheese! +${hp} HP`,
  sayAte: () => 'Yummy.',
  cheese: 'Fried cheese',
  notBuyZone: 'You are not in the buy zone',
  buyExpired: 'The buy time has expired',
  buyFail: (r) => r,
  lang: 'en-US',
};

const BUY_FAIL = {
  'Not enough money': 'Ňemaš peňeži, chudaku!',
  'Not in buy zone / buy time over': 'Tu še ňekupuje, ty ľemro!',
  'Already have armor': 'Už maš vestu, ta co ešči chceš?',
  'Already have a kit': 'Kit už maš, ňebuď chamtivi.',
  'CT only': 'To ľem pre policajtov, ty zbojňiku!',
  'Wrong team': 'To ňe pre tvoju partiju!',
  'Cannot carry more': 'Vecej ňeuňešeš, ši ňe mul!',
  'Already have it': 'Ta šak to už maš, debiľe!',
};

const ANN_VYCH = {
  matchStart: () => pick(['Začina še to, kurva!', 'Ta idzeme, lemre, zapas začina!', 'Poďce še bic, kurvy!']),
  round: (n) => `Kolo ${n}`,
  buyPhase: 'Kupuj, ľem ňeprejebaj šicki peňeži — <b>B</b>',
  go: () => pick(['Idzeme, kurva, idzeme!', 'Napredok, lemre!', 'Bežce, kurvy, bežce!']),
  planted: 'Bomba je podložena!',
  plantedSub: (s) => `Na ${s} · 40 sekund, bežce do rici`,
  win: (team) => (team === 'T' ? 'Teroristi vyhrali' : 'Protiteroristi vyhrali'),
  reasons: {
    elim: 'Šicki su pobiti, ta co',
    bomb: 'Buchlo to jak na Silvestra',
    defuse: 'Bomba zneškodnena, ta vidziš',
    time: 'Čas vypršal, ta co ste robili, lemry?',
  },
  mvp: 'Najlepši chlop',
  killedBy: (k, w, hs) => `Zabil ce ${k} · ${w}${hs ? ' · rovno do hlavy' : ''}`,
  died: 'Ta ši mertvi, ty ľemro',
  sayPlanted: () => pick(['Bomba je podložena, bežce do rici!', 'Bomba tika, kurva, kto ju ňezneškodňi, ten lemra!', 'Podložene! Šicki bežce, lebo buchňe!']),
  sayDefused: () => pick(['Bomba je zneškodnena, ta vidzice.', 'Zneškodnene, teroristi idu plakac!', 'Drotiky prestrihnute, kurva drat!']),
  sayWin: (team) => pick(team === 'T'
    ? ['Teroristi vyhrali, kurva drat!', 'Teroristi vyhrali, policajti idu domu plakac!', 'Teroristi to zrobili, jebem vas, policajti!']
    : ['Protiteroristi vyhrali, ta ňeplačce.', 'Protiteroristi vyhrali, teroristi, idzce še schovac!', 'Policajti vyhrali, a teroristi su v riti!']),
  sayNade: { he: 'Granat leci, chovajce rici!', flash: 'Flešak, zatvarajce oči!', smoke: 'Dimovnica leci!' },
  ate: (hp) => `Vyprážaný syr! +${hp} HP, mňam!`,
  sayAte: () => pick(['Mňam!', 'Mňam, to je syr!', 'Kurva, to je dobre!']),
  cheese: 'Vyprážaný syr',
  notBuyZone: 'Tu še ňekupuje, ty ľemro!',
  buyExpired: 'Kupovanie skončilo, trebalo še pohnuc!',
  buyFail: (r) => BUY_FAIL[r] || r,
  lang: 'sk-SK',
};

export function announcer(dialect) {
  return dialect ? ANN_VYCH : ANN_EN;
}
